name: ${PROJECT_NAME}

services:
  ui:
    environment:
      - ENVIRONMENT=production

  api:
    environment:
      - ENVIRONMENT=production

  celeryworker:
    environment:
      - ENVIRONMENT=production

networks:
  net:
    name: ${PROJECT_NAME}_network
    driver: bridge
    ipam:
      driver: default
