name: ${PROJECT_NAME}

services:
  frontend:
    environment:
      - ENVIRONMENT=production

  backend:
    environment:
      - ENVIRONMENT=production

networks:
  net:
    name: ${PROJECT_NAME}_network
    driver: bridge
    ipam:
      driver: default
