x-kafka-env: &kafka-env
  KAFKA_CFG_PROCESS_ROLES: controller,broker
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@${PROJECT_NAME}_kafka0:9093,2@${PROJECT_NAME}_kafka1:9093,3@${PROJECT_NAME}_kafka2:9093
  KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
  KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true

services:
  kafka0:
    image: bitnami/kafka:latest
    container_name: ${PROJECT_NAME}_kafka0
    environment:
      <<: *kafka-env
      KAFKA_KRAFT_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://${PROJECT_NAME}_kafka0:9092,CONTROLLER://${PROJECT_NAME}_kafka0:9093
    volumes:
      - kfdata0:/bitnami/kafka
    networks:
      - net
    restart: always

  kafka1:
    image: bitnami/kafka:latest
    container_name: ${PROJECT_NAME}_kafka1
    environment:
      <<: *kafka-env
      KAFKA_KRAFT_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://${PROJECT_NAME}_kafka1:9092,CONTROLLER://${PROJECT_NAME}_kafka1:9093
    volumes:
      - kfdata1:/bitnami/kafka
    networks:
      - net
    restart: always

  kafka2:
    image: bitnami/kafka:latest
    container_name: ${PROJECT_NAME}_kafka2
    environment:
      <<: *kafka-env
      KAFKA_KRAFT_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_CFG_NODE_ID: 3
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://${PROJECT_NAME}_kafka2:9092,CONTROLLER://${PROJECT_NAME}_kafka2:9093
    volumes:
      - kfdata2:/bitnami/kafka
    networks:
      - net
    restart: always

volumes:
  kfdata0:
    driver: local
  kfdata1:
    driver: local
  kfdata2:
    driver: local
