services:
  ui:
    environment:
      - IS_OLLAMA_RUNNING=true

  api:
    environment:
      - OLLAMA_API_URL=http://${PROJECT_NAME}_ollama:11434

  celeryworker:
    environment:
      - OLLAMA_API_URL=http://${PROJECT_NAME}_ollama:11434

  socket:
    environment:
      - OLLAMA_API_URL=http://${PROJECT_NAME}_ollama:11434
