name: ${PROJECT_NAME}

services:
  server:
    command: [nginx-debug, "-g", "daemon off;"]

  ui:
    environment:
      - ENVIRONMENT=development

  api:
    environment:
      - ENVIRONMENT=development

  celeryworker:
    environment:
      - ENVIRONMENT=development

networks:
  net:
    name: ${PROJECT_NAME}_network
    driver: bridge
    ipam:
      driver: default
