services:
  zookeeper0:
    init: true
    image: bitnami/zookeeper:latest
    container_name: ${PROJECT_NAME}_zookeeper0
    environment:
      - ZOO_PORT_NUMBER=2181
      - ZOO_TICK_TIME=${ZOOKEEPER_TICK_TIME:-2000}
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - net
    volumes:
      - zoodata0:/bitnami/zookeeper
    restart: always

  zookeeper1:
    init: true
    image: bitnami/zookeeper:latest
    container_name: ${PROJECT_NAME}_zookeeper1
    environment:
      - ZOO_PORT_NUMBER=2181
      - ZOO_TICK_TIME=${ZOOKEEPER_TICK_TIME:-2000}
      - ZOO_SERVER_ID=2
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - net
    volumes:
      - zoodata1:/bitnami/zookeeper
    restart: always

  zookeeper2:
    init: true
    image: bitnami/zookeeper:latest
    container_name: ${PROJECT_NAME}_zookeeper2
    environment:
      - ZOO_PORT_NUMBER=2181
      - ZOO_TICK_TIME=${ZOOKEEPER_TICK_TIME:-2000}
      - ZOO_SERVER_ID=3
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - net
    volumes:
      - zoodata2:/bitnami/zookeeper
    restart: always

  kafka0:
    init: true
    image: bitnami/kafka:3.9
    container_name: ${PROJECT_NAME}_kafka0
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ZOOKEEPER_CONNECT=${PROJECT_NAME}_zookeeper0:2181,${PROJECT_NAME}_zookeeper1:2181,${PROJECT_NAME}_zookeeper2:2181
      - KAFKA_ZOOKEEPER_PROTOCOL=PLAINTEXT
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${PROJECT_NAME}_kafka0:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://${PROJECT_NAME}_kafka0:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENER_NAME=PLAINTEXT
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
      - net
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    volumes:
      - kfdata0:/bitnami/kafka/data
    restart: always

  kafka1:
    init: true
    image: bitnami/kafka:3.9
    container_name: ${PROJECT_NAME}_kafka1
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ZOOKEEPER_CONNECT=${PROJECT_NAME}_zookeeper0:2181,${PROJECT_NAME}_zookeeper1:2181,${PROJECT_NAME}_zookeeper2:2181
      - KAFKA_ZOOKEEPER_PROTOCOL=PLAINTEXT
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${PROJECT_NAME}_kafka1:29092,PLAINTEXT_HOST://localhost:9093
      - KAFKA_LISTENERS=PLAINTEXT://${PROJECT_NAME}_kafka1:29092,PLAINTEXT_HOST://localhost:9093
      - KAFKA_LISTENER_NAME=PLAINTEXT
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
      - net
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    volumes:
      - kfdata1:/bitnami/kafka/data
    restart: always

  kafka2:
    init: true
    image: bitnami/kafka:3.9
    container_name: ${PROJECT_NAME}_kafka2
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ZOOKEEPER_CONNECT=${PROJECT_NAME}_zookeeper0:2181,${PROJECT_NAME}_zookeeper1:2181,${PROJECT_NAME}_zookeeper2:2181
      - KAFKA_ZOOKEEPER_PROTOCOL=PLAINTEXT
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${PROJECT_NAME}_kafka2:29092,PLAINTEXT_HOST://localhost:9094
      - KAFKA_LISTENERS=PLAINTEXT://${PROJECT_NAME}_kafka2:29092,PLAINTEXT_HOST://localhost:9094
      - KAFKA_LISTENER_NAME=PLAINTEXT
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
      - net
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    volumes:
      - kfdata2:/bitnami/kafka/data
    restart: always

volumes:
  zoodata0:
    driver: local
  zoodata1:
    driver: local
  zoodata2:
    driver: local
  kfdata0:
    driver: local
  kfdata1:
    driver: local
  kfdata2:
    driver: local
