"""empty message

Revision ID: c192eeaf2635
Revises: 37e5e9efe242
Create Date: 2025-10-02 08:00:28.430596

"""

from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c192eeaf2635"
down_revision: Union[str, None] = "37e5e9efe242"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project_assigned_internal_bot", sa.Column("prompt", sa.Text(), nullable=False, server_default=""))
    op.add_column(
        "project_assigned_internal_bot",
        sa.Column("use_default_prompt", sa.Boolean(), nullable=False, server_default="1"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_assigned_internal_bot", "use_default_prompt")
    op.drop_column("project_assigned_internal_bot", "prompt")
    # ### end Alembic commands ###
