"""empty message

Revision ID: 1b6e20e2583e
Revises: c09218ff8145
Create Date: 2025-10-10 11:38:38.579717

"""

from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "1b6e20e2583e"
down_revision: Union[str, None] = "c09218ff8145"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_activity", schema=None) as batch_op:
        batch_op.add_column(sa.Column("project_column_id", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_activity", schema=None) as batch_op:
        batch_op.drop_column("project_column_id")

    # ### end Alembic commands ###
