import "@/validators/AppSettings";
import "@/validators/Board";
import "@/validators/BoardCard";
import "@/validators/BoardSettings";
import "@/validators/BoardWiki";
import "@/validators/BoardWikiPrivate";
import "@/validators/Dashboard";
import "@/validators/User";
import "@/validators/UserPrivate";
