export const API_ROUTES = {
    AUTH: {
        EMAIL: "/auth/email",
        SIGN_IN: "/auth/signin",
        REFRESH: "/auth/refresh",
        ABOUT_ME: "/auth/me",
        RECOVERY: {
            SEND_LINK: "/auth/recovery/send",
            VALIDATE: "/auth/recovery/validate",
            RESET: "/auth/recovery/reset",
        },
        SIGN_UP: {
            SEND_LINK: "/auth/signup",
            ACTIVATE: "/auth/signup/activate",
            EXISTS_EMAIL: "/auth/signup/exist/email",
            RESEND_LINK: "/auth/signup/resend",
        },
    },
    ACCOUNT: {
        GET_SUBEMAILS: "/account/subemails",
        UPDATE_PROFILE: "/account/profile",
        CHANGE_PASSWORD: "/account/password",
        EMAIL: {
            CRUD: "/account/email",
            VERIFY: "/account/email/verify",
        },
        USER_GROUP: {
            UPDATE_ASSIGNED_EMAILS: "/account/group/{group_uid}/emails",
        },
    },
    ACTIVITIY: {
        USER: "/activity/user",
        CARD: "/activity/project/{uid}/card/{card_uid}",
    },
    DASHBOARD: {
        ALL_STARRED_PROJECTS: "/dashboard/user/projects/starred",
        PROJECTS: "/dashboard/projects",
        TOGGLE_STAR_PROJECT: "/dashboard/projects/{uid}/star",
        CREATE_PROJECT: "/dashboard/projects/new",
    },
    BOARD: {
        GET: "/board/{uid}",
        IS_AVAILABLE: "/board/{uid}/available",
        CAN_USE_SETTINGS: "/board/{uid}/settings/available",
        CHAT_MESSAGES: "/board/{uid}/chat",
        CLEAR_CHAT_MESSAGES: "/board/{uid}/chat/clear",
        GET_CARDS: "/board/{uid}/cards",
        GET_COLUMN_CARDS: "/board/{uid}/column/{column_uid}/cards",
        UPDATE_ASSIGNED_USERS: "/board/{uid}/assigned-users",
        ACCEPT_INVITATION: "/project/invite/accept",
        COLUMN: {
            CREATE: "/board/{uid}/column",
            CHANGE_NAME: "/board/{uid}/column/{column_uid}/name",
            CHANGE_ORDER: "/board/{uid}/column/{column_uid}/order",
        },
        CARD: {
            CREATE: "/board/{uid}/card",
            CHANGE_ORDER: "/board/{uid}/card/{card_uid}/order",
            GET_DETAILS: "/board/{uid}/card/{card_uid}",
            CHANGE_DETAILS: "/board/{uid}/card/{card_uid}/details",
            UPDATE_ASSIGNED_USERS: "/board/{uid}/card/{card_uid}/assigned-users",
            UPDATE_LABELS: "/board/{uid}/card/{card_uid}/labels",
            UPDATE_RELATIONSHIPS: "/board/{uid}/card/{card_uid}/relationships",
            ATTACHMENT: {
                UPLOAD: "/board/{uid}/card/{card_uid}/attachment",
                CHANGE_NAME: "/board/{uid}/card/{card_uid}/attachment/{attachment_uid}/name",
                CHANGE_ORDER: "/board/{uid}/card/{card_uid}/attachment/{attachment_uid}/order",
                DELETE: "/board/{uid}/card/{card_uid}/attachment/{attachment_uid}",
            },
            COMMENT: {
                GET_LIST: "/board/{uid}/card/{card_uid}/comments",
                ADD: "/board/{uid}/card/{card_uid}/comment",
                UPDATE: "/board/{uid}/card/{card_uid}/comment/{comment_uid}",
                DELETE: "/board/{uid}/card/{card_uid}/comment/{comment_uid}",
                REACT: "/board/{uid}/card/{card_uid}/comment/{comment_uid}/react",
            },
            CHECKITEM: {
                CREATE: "/board/{uid}/card/{card_uid}/checkitem",
                CHANGE_TITLE: "/board/{uid}/card/{card_uid}/checkitem/{checkitem_uid}/title",
                CHANGE_ORDER: "/board/{uid}/card/{card_uid}/checkitem/{checkitem_uid}/order",
                CARDIFY: "/board/{uid}/card/{card_uid}/checkitem/{checkitem_uid}/cardify",
                DELETE: "/board/{uid}/card/{card_uid}/checkitem/{checkitem_uid}",
                TOGGLE_TIMER: "/board/{uid}/card/{card_uid}/checkitem/{checkitem_uid}/timer/toggle",
            },
            SUB_CHECKITEM: {
                CREATE: "/board/{uid}/card/{card_uid}/checkitem/{checkitem_uid}/sub-checkitem",
                CHANGE_ORDER: "/board/{uid}/card/{card_uid}/sub-checkitem/{sub_checkitem_uid}/order",
            },
        },
        WIKI: {
            GET_ALL: "/board/{uid}/wikis",
            CREATE: "/board/{uid}/wiki",
            UPLOAD: "/board/{uid}/wiki/{wiki_uid}/attachment",
            CHANGE_DETAILS: "/board/{uid}/wiki/{wiki_uid}/details",
            CHANGE_ORDER: "/board/{uid}/wiki/{wiki_uid}/order",
            CHANGE_PUBLIC: "/board/{uid}/wiki/{wiki_uid}/public",
            UPDATE_ASSIGNED_USERS: "/board/{uid}/wiki/{wiki_uid}/assigned-users",
            DELETE: "/board/{uid}/wiki/{wiki_uid}",
        },
        SETTINGS: {
            UPDATE_DETAILS: "/board/{uid}/settings/details",
            LABEL: {
                CREATE: "/board/{uid}/settings/label",
                CHANGE_DETAILS: "/board/{uid}/settings/label/{label_uid}/details",
                CHANGE_ORDER: "/board/{uid}/settings/label/{label_uid}/order",
                DELETE: "/board/{uid}/settings/label/{label_uid}",
            },
        },
    },
    REVERT: (path: string) => `/revert/${path}`,
} as const;

export const SOCKET_SERVER_EVENTS = {
    PROJECT: {
        TITLE_CHANGED: "project:title:changed:{uid}",
        DESCRIPTION_CHANGED: "project:description:changed:{uid}",
        TYPE_CHANGED: "project:project_type:changed:{uid}",
        AI_DESCRIPTION_CHANGED: "project:ai_description:changed:{uid}",
        COLUMN: {
            CREATED: "project:column:created:{uid}",
            NAME_CHANGED: "project:column:name:changed:{uid}",
            ORDER_CHANGED: "project:column:order:changed:{uid}",
        },
        LABEL: {
            CREATED: "project:label:created:{uid}",
            NAME_CHANGED: "project:label:name:changed:{uid}",
            COLOR_CHANGED: "project:label:color:changed:{uid}",
            DESCRIPTION_CHANGED: "project:label:description:changed:{uid}",
            ORDER_CHANGED: "project:label:order:changed:{uid}",
            DELETED: "project:label:deleted:{uid}",
        },
    },
    DASHBOARD: {
        CARD: {
            CREATED: "dashboard:card:created:{uid}",
            ORDER_CHANGED: "dashboard:card:order:changed:{uid}",
        },
    },
    BOARD: {
        IS_CHAT_AVAILABLE: "board:chat:available",
        CHAT_SENT: "board:chat:sent",
        CHAT_STREAM: "board:chat:stream",
        ASSIGNED_USERS_UPDATED: "board:assigned-users:updated:{uid}",
        CARD: {
            CREATED: "board:card:created:{uid}",
            ORDER_CHANGED: "board:card:order:changed:{uid}",
            TITLE_CHANGED: "board:card:title:changed:{uid}",
            DEADLINE_CHANGED: "board:card:deadline_at:changed:{uid}",
            DESCRIPTION_CHANGED: "board:card:description:changed:{uid}",
            ASSIGNED_USERS_UPDATED: "board:card:assigned-users:updated:{uid}",
            RELATIONSHIPS_UPDATED: "board:card:relationships:updated:{uid}",
            LABELS_UPDATED: "board:card:labels:updated:{uid}",
            EDITOR_USERS: "board:card:editor:users:{uid}",
            EDITOR_START_EDITING: "board:card:editor:start:{uid}",
            EDITOR_STOP_EDITING: "board:card:editor:stop:{uid}",
            ATTACHMENT: {
                UPLOADED: "board:card:attachment:uploaded",
                NAME_CHANGED: "board:card:attachment:name:changed:{uid}",
                ORDER_CHANGED: "board:card:attachment:order:changed",
                DELETED: "board:card:attachment:deleted",
            },
            COMMENT: {
                ADDED: "board:card:comment:added:{uid}",
                UPDATED: "board:card:comment:updated:{uid}",
                DELETED: "board:card:comment:deleted:{uid}",
                REACTED: "board:card:comment:reacted:{uid}",
            },
            CHECKITEM: {
                CREATED: "board:card:checkitem:created:{uid}",
                TITLE_CHANGED: "board:card:checkitem:title:changed:{uid}",
                ORDER_CHANGED: "board:card:checkitem:order:changed:{uid}",
                ASSIGNED_USERS_UPDATED: "board:card:checkitem:assigned-users:updated:{uid}",
                CARDIFIED: "board:card:checkitem:cardified:{uid}",
                DELETED: "board:card:checkitem:deleted:{uid}",
                TIMER_STARTED: "board:card:checkitem:timer:started:{uid}",
                TIMER_STOPPED: "board:card:checkitem:timer:stopped:{uid}",
            },
            SUB_CHECKITEM: {
                CREATED: "board:card:sub-checkitem:created:{uid}",
                ORDER_CHANGED: "board:card:sub-checkitem:order:changed:{uid}",
            },
        },
        WIKI: {
            CREATED: "board:wiki:created:{uid}",
            EDITOR_USERS: "board:wiki:editor:users:{uid}",
            EDITOR_START_EDITING: "board:wiki:editor:start:{uid}",
            EDITOR_STOP_EDITING: "board:wiki:editor:stop:{uid}",
            TITLE_CHANGED: "board:wiki:title:changed:{uid}",
            CONTENT_CHANGED: "board:wiki:content:changed:{uid}",
            PUBLIC_CHANGED: "board:wiki:public:changed:{uid}",
            ASSIGNED_USERS_UPDATED: "board:wiki:assigned-users:updated:{uid}",
            ORDER_CHANGED: "board:wiki:order:changed:{uid}",
            DELETED: "board:wiki:deleted:{uid}",
        },
    },
} as const;

export const SOCKET_CLIENT_EVENTS = {
    BOARD: {
        IS_CHAT_AVAILABLE: "board:chat:available",
        CHAT_SEND: "board:chat:send",
        CARD: {
            EDITOR_USERS: "board:card:editor:users",
            EDITOR_START_EDITING: "board:card:editor:start",
            EDITOR_STOP_EDITING: "board:card:editor:stop",
        },
        WIKI: {
            EDITOR_USERS: "board:wiki:editor:users",
            EDITOR_START_EDITING: "board:wiki:editor:start",
            EDITOR_STOP_EDITING: "board:wiki:editor:stop",
        },
    },
} as const;
