export const API_ROUTES = {
    AUTH: {
        EMAIL: "/auth/email",
        SIGN_IN: "/auth/signin",
        REFRESH: "/auth/refresh",
        ABOUT_ME: "/auth/me",
        RECOVERY: {
            SEND_LINK: "/auth/recovery/send",
            VALIDATE: "/auth/recovery/validate",
            RESET: "/auth/recovery/reset",
        },
        SIGN_UP: {
            SEND_LINK: "/auth/signup",
            ACTIVATE: "/auth/signup/activate",
            EXISTS_EMAIL: "/auth/signup/exist/email",
            RESEND_LINK: "/auth/signup/resend",
        },
    },
    ACCOUNT: {
        GET_SUBEMAILS: "/account/subemails",
        UPDATE_PROFILE: "/account/profile",
        CHANGE_PASSWORD: "/account/password",
        UPDATE_PREFERRED_LANGUAGE: "/account/preferred-language",
        EMAIL: {
            CRUD: "/account/email",
            VERIFY: "/account/email/verify",
        },
        USER_GROUP: {
            CREATE: "/account/group",
            CHANGE_NAME: "/account/group/{group_uid}/name",
            UPDATE_ASSIGNED_EMAILS: "/account/group/{group_uid}/emails",
            DELETE: "/account/group/{group_uid}",
        },
    },
    NOTIFICATION: {
        SETTINGS: {
            ALL: "/notification/setting/all",
            TYPE: "/notification/setting/type",
            ALL_PROJECT: "/notification/setting/project",
            PROJECT: "/notification/setting/project/{uid}",
            ALL_COLUMN: "/notification/setting/column",
            COLUMN: "/notification/setting/project/{uid}/column/{column_uid}",
            ALL_CARD: "/notification/setting/card",
            CARD: "/notification/setting/project/{uid}/card/{card_uid}",
            ALL_WIKI: "/notification/setting/wiki",
            WIKI: "/notification/setting/project/{uid}/wiki/{wiki_uid}",
        },
    },
    ACTIVITIY: {
        USER: "/activity/user",
        PROJECT: "/activity/project/{uid}",
        CARD: "/activity/project/{uid}/card/{card_uid}",
        PROJECT_WIKI: "/activity/project/{uid}/wiki/{wiki_uid}",
        PROJECT_ASSIGNEE: "/activity/project/{uid}/assignee/{assignee_uid}",
    },
    DASHBOARD: {
        ALL_STARRED_PROJECTS: "/dashboard/user/projects/starred",
        PROJECTS: "/dashboard/projects",
        TOGGLE_STAR_PROJECT: "/dashboard/projects/{uid}/star",
        CREATE_PROJECT: "/dashboard/projects/new",
        CARDS: "/dashboard/cards",
        TRACKING: "/dashboard/tracking",
    },
    BOARD: {
        GET: "/board/{uid}",
        DETAILS: "/board/{uid}/details",
        GET_INVITATION: "/project/invite/details/{token}",
        IS_AVAILABLE: "/board/{uid}/available",
        IS_PROJECT_ASSIGNEE: "/board/{uid}/is-assigned/{assignee_uid}",
        CHAT_MESSAGES: "/board/{uid}/chat",
        CLEAR_CHAT_MESSAGES: "/board/{uid}/chat/clear",
        GET_CARDS: "/board/{uid}/cards",
        GET_COLUMN_CARDS: "/board/{uid}/column/{column_uid}/cards",
        UPDATE_ASSIGNED_USERS: "/board/{uid}/assigned-users",
        UNASSIGN_ASSIGNEE: "/board/{uid}/unassign/{assignee_uid}",
        ACCEPT_INVITATION: "/project/invite/accept",
        DECLINE_INVITATION: "/project/invite/decline",
        COLUMN: {
            CREATE: "/board/{uid}/column",
            CHANGE_NAME: "/board/{uid}/column/{column_uid}/name",
            CHANGE_ORDER: "/board/{uid}/column/{column_uid}/order",
            DELETE: "/board/{uid}/column/{column_uid}",
        },
        CARD: {
            CREATE: "/board/{uid}/card",
            CHANGE_ORDER: "/board/{uid}/card/{card_uid}/order",
            GET_DETAILS: "/board/{uid}/card/{card_uid}",
            CHANGE_DETAILS: "/board/{uid}/card/{card_uid}/details",
            UPDATE_ASSIGNED_USERS: "/board/{uid}/card/{card_uid}/assigned-users",
            UPDATE_LABELS: "/board/{uid}/card/{card_uid}/labels",
            UPDATE_RELATIONSHIPS: "/board/{uid}/card/{card_uid}/relationships",
            ARCHIVE: "/board/{uid}/card/{card_uid}/archive",
            DELETE: "/board/{uid}/card/{card_uid}",
            ATTACHMENT: {
                UPLOAD: "/board/{uid}/card/{card_uid}/attachment",
                CHANGE_NAME: "/board/{uid}/card/{card_uid}/attachment/{attachment_uid}/name",
                CHANGE_ORDER: "/board/{uid}/card/{card_uid}/attachment/{attachment_uid}/order",
                DELETE: "/board/{uid}/card/{card_uid}/attachment/{attachment_uid}",
            },
            COMMENT: {
                GET_LIST: "/board/{uid}/card/{card_uid}/comments",
                ADD: "/board/{uid}/card/{card_uid}/comment",
                UPDATE: "/board/{uid}/card/{card_uid}/comment/{comment_uid}",
                DELETE: "/board/{uid}/card/{card_uid}/comment/{comment_uid}",
                REACT: "/board/{uid}/card/{card_uid}/comment/{comment_uid}/react",
            },
            CHECKLIST: {
                CREATE: "/board/{uid}/card/{card_uid}/checklist",
                NOTIFY: "/board/{uid}/card/{card_uid}/checklist/{checklist_uid}/notify",
                CHANGE_TITLE: "/board/{uid}/card/{card_uid}/checklist/{checklist_uid}/title",
                CHANGE_ORDER: "/board/{uid}/card/{card_uid}/checklist/{checklist_uid}/order",
                TOGGLE_CHECKED: "/board/{uid}/card/{card_uid}/checklist/{checklist_uid}/toggle-checked",
                DELETE: "/board/{uid}/card/{card_uid}/checklist/{checklist_uid}",
            },
            CHECKITEM: {
                CREATE: "/board/{uid}/card/{card_uid}/checklist/{checklist_uid}/checkitem",
                CHANGE_TITLE: "/board/{uid}/card/{card_uid}/checkitem/{checkitem_uid}/title",
                CHANGE_ORDER: "/board/{uid}/card/{card_uid}/checkitem/{checkitem_uid}/order",
                CHANGE_STATUS: "/board/{uid}/card/{card_uid}/checkitem/{checkitem_uid}/status",
                TOGGLE_CHECKED: "/board/{uid}/card/{card_uid}/checkitem/{checkitem_uid}/toggle-checked",
                CARDIFY: "/board/{uid}/card/{card_uid}/checkitem/{checkitem_uid}/cardify",
                DELETE: "/board/{uid}/card/{card_uid}/checkitem/{checkitem_uid}",
            },
            SUB_CHECKITEM: {
                CREATE: "/board/{uid}/card/{card_uid}/checkitem/{checkitem_uid}/sub-checkitem",
                CHANGE_ORDER: "/board/{uid}/card/{card_uid}/sub-checkitem/{sub_checkitem_uid}/order",
            },
        },
        WIKI: {
            GET_ALL: "/board/{uid}/wikis",
            CREATE: "/board/{uid}/wiki",
            UPLOAD: "/board/{uid}/wiki/{wiki_uid}/attachment",
            CHANGE_DETAILS: "/board/{uid}/wiki/{wiki_uid}/details",
            CHANGE_ORDER: "/board/{uid}/wiki/{wiki_uid}/order",
            CHANGE_PUBLIC: "/board/{uid}/wiki/{wiki_uid}/public",
            UPDATE_ASSIGNEES: "/board/{uid}/wiki/{wiki_uid}/assignees",
            DELETE: "/board/{uid}/wiki/{wiki_uid}",
        },
        SETTINGS: {
            UPDATE_DETAILS: "/board/{uid}/settings/details",
            UPDATE_ASSIGNED_BOTS: "/board/{uid}/settings/assigned-bots",
            UPDATE_BOT_ROLES: "/board/{uid}/settings/roles/bot/{bot_uid}",
            UPDATE_USER_ROLES: "/board/{uid}/settings/roles/user/{user_uid}",
            TOGGLE_BOT_ACTIVATION: "/board/{uid}/settings/bot/{bot_uid}/toggle-activation",
            DELETE_PROJECT: "/board/{uid}/settings/delete",
            LABEL: {
                CREATE: "/board/{uid}/settings/label",
                CHANGE_DETAILS: "/board/{uid}/settings/label/{label_uid}/details",
                CHANGE_ORDER: "/board/{uid}/settings/label/{label_uid}/order",
                DELETE: "/board/{uid}/settings/label/{label_uid}",
            },
            BOT_SCHEDULE: {
                GET_ALL: "/board/{uid}/settings/bot/{bot_uid}/schedules",
                SCHEDULE: "/board/{uid}/settings/bot/{bot_uid}/schedule",
                RESCHEDULE: "/board/{uid}/settings/bot/{bot_uid}/reschedule/{schedule_uid}",
                UNSCHEDULE: "/board/{uid}/settings/bot/{bot_uid}/unschedule/{schedule_uid}",
            },
        },
    },
    SETTINGS: {
        IS_AVAILABLE: "/settings/available",
        GET_ALL: "/settings/all",
        CREATE: "/settings/app",
        UPDATE: "/settings/app/{uid}",
        DELETE: "/settings/app/{uid}",
        DELETE_SELECTED: "/settings/app",
        BOTS: {
            CREATE: "/settings/bot",
            UPDATE: "/settings/bot/{bot_uid}",
            GENERATE_NEW_API_TOKEN: "/settings/bot/{bot_uid}/new-api-token",
            TOGGLE_TRIGGER_CONDITION: "/settings/bot/{bot_uid}/trigger-condition",
            DELETE: "/settings/bot/{bot_uid}",
        },
        GLOBAL_RELATIONSHIPS: {
            CREATE: "/settings/global-relationship",
            UPDATE: "/settings/global-relationship/{uid}",
            DELETE: "/settings/global-relationship/{uid}",
            DELETE_SELECTED: "/settings/global-relationship",
        },
    },
} as const;

export const SOCKET_SERVER_EVENTS = {
    DASHBOARD: {
        PROJECT: {
            ASSIGNED_USERS_UPDATED: "dashboard:project:assigned-users:updated:{uid}",
            DELETED: "dashboard:project:deleted:{uid}",
            COLUMN: {
                CREATED: "dashboard:project:column:created:{uid}",
                NAME_CHANGED: "dashboard:project:column:name:changed:{uid}",
                ORDER_CHANGED: "dashboard:project:column:order:changed:{uid}",
                DELETED: "dashboard:project:column:deleted:{uid}",
            },
        },
        CARD: {
            CREATED: "dashboard:card:created:{uid}",
            TITLE_CHANGED: "dashboard:card:title:changed:{uid}",
            ORDER_CHANGED: "dashboard:card:order:changed:{uid}",
            DELETED: "dashboard:card:deleted:{uid}",
        },
        CHECKITEM: {
            TITLE_CHANGED: "dashboard:checkitem:title:changed:{uid}",
            STATUS_CHANGED: "dashboard:checkitem:status:changed:{uid}",
            CHECKED_CHANGED: "dashboard:checkitem:checked:changed:{uid}",
            DELETED: "dashboard:checkitem:deleted:{uid}",
        },
    },
    BOARD: {
        IS_CHAT_AVAILABLE: "board:chat:available",
        CHAT_SENT: "board:chat:sent",
        CHAT_CANCELLED: "board:chat:cancelled",
        CHAT_STREAM: "board:chat:stream",
        ASSIGNED_USERS_UPDATED: "board:assigned-users:updated:{uid}",
        ASSIGNED_BOTS_UPDATED: "board:assigned-bots:updated:{uid}",
        BOT_ROLES_UPDATED: "board:roles:bot:updated:{uid}",
        USER_ROLES_UPDATED: "board:roles:user:updated:{uid}",
        DETAILS_CHANGED: "board:details:changed:{uid}",
        DELETED: "board:deleted:{uid}",
        LABEL: {
            CREATED: "board:label:created:{uid}",
            DETAILS_CHANGED: "board:label:details:changed:{uid}",
            ORDER_CHANGED: "board:label:order:changed:{uid}",
            DELETED: "board:label:deleted:{uid}",
        },
        COLUMN: {
            CREATED: "board:column:created:{uid}",
            NAME_CHANGED: "board:column:name:changed:{uid}",
            ORDER_CHANGED: "board:column:order:changed:{uid}",
            DELETED: "board:column:deleted:{uid}",
        },
        CARD: {
            CREATED: "board:card:created:{uid}",
            ORDER_CHANGED: "board:card:order:changed:{uid}",
            DETAILS_CHANGED: "board:card:details:changed:{uid}",
            ASSIGNED_USERS_UPDATED: "board:card:assigned-users:updated:{uid}",
            RELATIONSHIPS_UPDATED: "board:card:relationships:updated:{uid}",
            LABELS_UPDATED: "board:card:labels:updated:{uid}",
            EDITOR_USERS: "board:card:editor:users:{uid}",
            EDITOR_START_EDITING: "board:card:editor:start:{uid}",
            EDITOR_STOP_EDITING: "board:card:editor:stop:{uid}",
            DELETED: "board:card:deleted:{uid}",
            ATTACHMENT: {
                UPLOADED: "board:card:attachment:uploaded",
                NAME_CHANGED: "board:card:attachment:name:changed:{uid}",
                ORDER_CHANGED: "board:card:attachment:order:changed",
                DELETED: "board:card:attachment:deleted",
            },
            COMMENT: {
                ADDED: "board:card:comment:added:{uid}",
                UPDATED: "board:card:comment:updated:{uid}",
                DELETED: "board:card:comment:deleted:{uid}",
                REACTED: "board:card:comment:reacted:{uid}",
            },
            CHECKLIST: {
                CREATED: "board:card:checklist:created:{uid}",
                TITLE_CHANGED: "board:card:checklist:title:changed:{uid}",
                ORDER_CHANGED: "board:card:checklist:order:changed:{uid}",
                CHECKED_CHANGED: "board:card:checklist:checked:changed:{uid}",
                DELETED: "board:card:checklist:deleted:{uid}",
            },
            CHECKITEM: {
                CREATED: "board:card:checkitem:created:{uid}",
                TITLE_CHANGED: "board:card:checkitem:title:changed:{uid}",
                ORDER_CHANGED: "board:card:checkitem:order:changed:{uid}",
                STATUS_CHANGED: "board:card:checkitem:status:changed:{uid}",
                CHECKED_CHANGED: "board:card:checkitem:checked:changed:{uid}",
                CARDIFIED: "board:card:checkitem:cardified:{uid}",
                DELETED: "board:card:checkitem:deleted:{uid}",
            },
        },
        WIKI: {
            CREATED: "board:wiki:created:{uid}",
            GOT_DETAILS: "board:wiki:details:{uid}",
            EDITOR_USERS: "board:wiki:editor:users:{uid}",
            EDITOR_START_EDITING: "board:wiki:editor:start:{uid}",
            EDITOR_STOP_EDITING: "board:wiki:editor:stop:{uid}",
            DETAILS_CHANGED: "board:wiki:details:changed:{uid}",
            PUBLIC_CHANGED: "board:wiki:public:changed:{uid}",
            ASSIGNEES_UPDATED: "board:wiki:assignees:updated:{uid}",
            PROJECT_USERS_UPDATED: "board:wiki:project-users:updated:{uid}",
            ORDER_CHANGED: "board:wiki:order:changed:{uid}",
            DELETED: "board:wiki:deleted:{uid}",
        },
        SETTINGS: {
            BOT_ACTIVATION_TOGGLED: "board:settings:activation:bot:toggled:{uid}",
            BOT_CRON: {
                SCHEDULED: "board:settings:bot:cron:scheduled:{uid}",
                RESCHEDULED: "board:settings:bot:cron:rescheduled:{uid}",
                DELETED: "board:settings:bot:cron:deleted:{uid}",
            },
        },
    },
    USER: {
        UPDATED: "user:updated",
        NOTIFIED: "user:notified",
        NOTIFICATION_DELETED: "user:notification:deleted",
        PROJECT_ROLES_UPDATED: "user:project-roles:updated",
    },
    GLOBALS: {
        BOTS: {
            CREATED: "settings:bot:created",
            UPDATED: "settings:bot:updated:{uid}",
            DELETED: "settings:bot:deleted:{uid}",
        },
        GLOBAL_RELATIONSHIPS: {
            CREATED: "settings:global-relationship:created",
            UPDATED: "settings:global-relationship:updated:{uid}",
            DELETED: "settings:global-relationship:deleted:{uid}",
            SELECTIONS_DELETED: "settings:global-relationship:deleted",
        },
    },
    PROJECT_BOT: {
        ACTIVATION_TOGGLED: "project:bot:activation:toggled:{uid}",
    },
} as const;

export const SOCKET_CLIENT_EVENTS = {
    BOARD: {
        IS_CHAT_AVAILABLE: "board:chat:available",
        CHAT_SEND: "board:chat:send",
        CHAT_CANCEL: "board:chat:cancel",
        CARD: {
            EDITOR_USERS: "board:card:editor:users",
            EDITOR_START_EDITING: "board:card:editor:start",
            EDITOR_STOP_EDITING: "board:card:editor:stop",
        },
        WIKI: {
            GET_DETAILS: "board:wiki:details",
            EDITOR_USERS: "board:wiki:editor:users",
            EDITOR_START_EDITING: "board:wiki:editor:start",
            EDITOR_STOP_EDITING: "board:wiki:editor:stop",
        },
    },
    USER: {
        READ_NOTIFICATION: "user:notification:read",
        READ_ALL_NOTIFICATIONS: "user:notification:read-all",
        DELETE_NOTIFICATION: "user:notification:delete",
        DELETE_ALL_NOTIFICATIONS: "user:notification:delete-all",
    },
} as const;
